//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.InterDF.Site.InterpretacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/InterpretacionService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vBuscaEnRevision", Namespace="http://schemas.datacontract.org/2004/07/FUJIFILM.InterpretacionesDF.DataAccess")]
    [System.SerializableAttribute()]
    public partial class vBuscaEnRevision : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmissionTimeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttendingPhysicianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttendingPhysicianIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentLocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalPatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalPatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastMenstruationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PregnancyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryLocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcedureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcedureDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RISOderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonForExamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferringPhysicianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferringPhysicianIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestingPhysicianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestingPhysicianIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyImageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudySiteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudyTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisitClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisitNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bkStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechayhoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oeComentarioValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> oeInterpretacionAprobadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioDictoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioDictoApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioDictoApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioDictoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioRevisoApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioRevisoApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioRevisoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioRevisoNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessionNumber {
            get {
                return this.AccessionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessionNumberField, value) != true)) {
                    this.AccessionNumberField = value;
                    this.RaisePropertyChanged("AccessionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmissionTimeDate {
            get {
                return this.AdmissionTimeDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmissionTimeDateField, value) != true)) {
                    this.AdmissionTimeDateField = value;
                    this.RaisePropertyChanged("AdmissionTimeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttendingPhysician {
            get {
                return this.AttendingPhysicianField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendingPhysicianField, value) != true)) {
                    this.AttendingPhysicianField = value;
                    this.RaisePropertyChanged("AttendingPhysician");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttendingPhysicianId {
            get {
                return this.AttendingPhysicianIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendingPhysicianIdField, value) != true)) {
                    this.AttendingPhysicianIdField = value;
                    this.RaisePropertyChanged("AttendingPhysicianId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentLocId {
            get {
                return this.CurrentLocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentLocIdField, value) != true)) {
                    this.CurrentLocIdField = value;
                    this.RaisePropertyChanged("CurrentLocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentLocationField, value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalPatientID {
            get {
                return this.ExternalPatientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalPatientIDField, value) != true)) {
                    this.ExternalPatientIDField = value;
                    this.RaisePropertyChanged("ExternalPatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalPatientID {
            get {
                return this.InternalPatientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalPatientIDField, value) != true)) {
                    this.InternalPatientIDField = value;
                    this.RaisePropertyChanged("InternalPatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastMenstruationDate {
            get {
                return this.LastMenstruationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastMenstruationDateField, value) != true)) {
                    this.LastMenstruationDateField = value;
                    this.RaisePropertyChanged("LastMenstruationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modality {
            get {
                return this.ModalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalityField, value) != true)) {
                    this.ModalityField = value;
                    this.RaisePropertyChanged("Modality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pregnancy {
            get {
                return this.PregnancyField;
            }
            set {
                if ((object.ReferenceEquals(this.PregnancyField, value) != true)) {
                    this.PregnancyField = value;
                    this.RaisePropertyChanged("Pregnancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryLocId {
            get {
                return this.PrimaryLocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryLocIdField, value) != true)) {
                    this.PrimaryLocIdField = value;
                    this.RaisePropertyChanged("PrimaryLocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryLocation {
            get {
                return this.PrimaryLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryLocationField, value) != true)) {
                    this.PrimaryLocationField = value;
                    this.RaisePropertyChanged("PrimaryLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcedureCode {
            get {
                return this.ProcedureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcedureCodeField, value) != true)) {
                    this.ProcedureCodeField = value;
                    this.RaisePropertyChanged("ProcedureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcedureDescription {
            get {
                return this.ProcedureDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcedureDescriptionField, value) != true)) {
                    this.ProcedureDescriptionField = value;
                    this.RaisePropertyChanged("ProcedureDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RISOderId {
            get {
                return this.RISOderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RISOderIdField, value) != true)) {
                    this.RISOderIdField = value;
                    this.RaisePropertyChanged("RISOderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonForExam {
            get {
                return this.ReasonForExamField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonForExamField, value) != true)) {
                    this.ReasonForExamField = value;
                    this.RaisePropertyChanged("ReasonForExam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferringPhysician {
            get {
                return this.ReferringPhysicianField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferringPhysicianField, value) != true)) {
                    this.ReferringPhysicianField = value;
                    this.RaisePropertyChanged("ReferringPhysician");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferringPhysicianId {
            get {
                return this.ReferringPhysicianIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferringPhysicianIdField, value) != true)) {
                    this.ReferringPhysicianIdField = value;
                    this.RaisePropertyChanged("ReferringPhysicianId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestingPhysician {
            get {
                return this.RequestingPhysicianField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestingPhysicianField, value) != true)) {
                    this.RequestingPhysicianField = value;
                    this.RaisePropertyChanged("RequestingPhysician");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestingPhysicianId {
            get {
                return this.RequestingPhysicianIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestingPhysicianIdField, value) != true)) {
                    this.RequestingPhysicianIdField = value;
                    this.RaisePropertyChanged("RequestingPhysicianId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((this.STATUSField.Equals(value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteCode {
            get {
                return this.SiteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteCodeField, value) != true)) {
                    this.SiteCodeField = value;
                    this.RaisePropertyChanged("SiteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyId {
            get {
                return this.StudyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyIdField, value) != true)) {
                    this.StudyIdField = value;
                    this.RaisePropertyChanged("StudyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyImageCount {
            get {
                return this.StudyImageCountField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyImageCountField, value) != true)) {
                    this.StudyImageCountField = value;
                    this.RaisePropertyChanged("StudyImageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudySiteName {
            get {
                return this.StudySiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudySiteNameField, value) != true)) {
                    this.StudySiteNameField = value;
                    this.RaisePropertyChanged("StudySiteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyStatusCode {
            get {
                return this.StudyStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyStatusCodeField, value) != true)) {
                    this.StudyStatusCodeField = value;
                    this.RaisePropertyChanged("StudyStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyTimeStamp {
            get {
                return this.StudyTimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyTimeStampField, value) != true)) {
                    this.StudyTimeStampField = value;
                    this.RaisePropertyChanged("StudyTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitClass {
            get {
                return this.VisitClassField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitClassField, value) != true)) {
                    this.VisitClassField = value;
                    this.RaisePropertyChanged("VisitClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitNumber {
            get {
                return this.VisitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitNumberField, value) != true)) {
                    this.VisitNumberField = value;
                    this.RaisePropertyChanged("VisitNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bkStatus {
            get {
                return this.bkStatusField;
            }
            set {
                if ((this.bkStatusField.Equals(value) != true)) {
                    this.bkStatusField = value;
                    this.RaisePropertyChanged("bkStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechayhora {
            get {
                return this.fechayhoraField;
            }
            set {
                if ((this.fechayhoraField.Equals(value) != true)) {
                    this.fechayhoraField = value;
                    this.RaisePropertyChanged("fechayhora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oeComentarioValidacion {
            get {
                return this.oeComentarioValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.oeComentarioValidacionField, value) != true)) {
                    this.oeComentarioValidacionField = value;
                    this.RaisePropertyChanged("oeComentarioValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> oeInterpretacionAprobada {
            get {
                return this.oeInterpretacionAprobadaField;
            }
            set {
                if ((this.oeInterpretacionAprobadaField.Equals(value) != true)) {
                    this.oeInterpretacionAprobadaField = value;
                    this.RaisePropertyChanged("oeInterpretacionAprobada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioDicto {
            get {
                return this.usuarioDictoField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioDictoField, value) != true)) {
                    this.usuarioDictoField = value;
                    this.RaisePropertyChanged("usuarioDicto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioDictoApellidoMaterno {
            get {
                return this.usuarioDictoApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioDictoApellidoMaternoField, value) != true)) {
                    this.usuarioDictoApellidoMaternoField = value;
                    this.RaisePropertyChanged("usuarioDictoApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioDictoApellidoPaterno {
            get {
                return this.usuarioDictoApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioDictoApellidoPaternoField, value) != true)) {
                    this.usuarioDictoApellidoPaternoField = value;
                    this.RaisePropertyChanged("usuarioDictoApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioDictoNombre {
            get {
                return this.usuarioDictoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioDictoNombreField, value) != true)) {
                    this.usuarioDictoNombreField = value;
                    this.RaisePropertyChanged("usuarioDictoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioRevisoApellidoMaterno {
            get {
                return this.usuarioRevisoApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioRevisoApellidoMaternoField, value) != true)) {
                    this.usuarioRevisoApellidoMaternoField = value;
                    this.RaisePropertyChanged("usuarioRevisoApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioRevisoApellidoPaterno {
            get {
                return this.usuarioRevisoApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioRevisoApellidoPaternoField, value) != true)) {
                    this.usuarioRevisoApellidoPaternoField = value;
                    this.RaisePropertyChanged("usuarioRevisoApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioRevisoID {
            get {
                return this.usuarioRevisoIDField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioRevisoIDField, value) != true)) {
                    this.usuarioRevisoIDField = value;
                    this.RaisePropertyChanged("usuarioRevisoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioRevisoNombre {
            get {
                return this.usuarioRevisoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioRevisoNombreField, value) != true)) {
                    this.usuarioRevisoNombreField = value;
                    this.RaisePropertyChanged("usuarioRevisoNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="opeUsuario", Namespace="http://schemas.datacontract.org/2004/07/FUJIFILM.InterpretacionesDF.DataAccess")]
    [System.SerializableAttribute()]
    public partial class opeUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FaltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FmodificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cmModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string csCveSitioAutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string csCveSitioDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> csSitioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> estRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> iduserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oeModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouAdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouAgendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouApellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouApellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouCamMedTraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouCamionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouCancelaEstudiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouCatalogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouCedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouConfirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouDictadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouDictadoNewLineModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouEditaEstudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouEsRecursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouEventosUrgenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouFinalizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouFirmaAusenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ouFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouGrabadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouHOVACamionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouHistotecnologoAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouHistotecnologoBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouIDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouIDChecadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouIdHisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouInicialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouInsertaAddendumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouLiberaEstudiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouListaTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouLoteGeneradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouMatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouModificaReportesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNUSA_applicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNUSA_habilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNUSA_languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNUSA_srcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNUSA_topicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNUSA_userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouPacientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouPatologoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouPerfilListaTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouReasignaIDPacientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouReportesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouResidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouSkinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouSobreturnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouTelefonoMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouTelefonoOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouTipodeDictadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouTranscriptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ouUaltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ouUmodificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouUrgenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ouUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouVeImagenesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouVocaliIntegracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouVocaliPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ouVocaliPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouVocaliServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouVocaliUSERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scValorDefaultEditorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Falta {
            get {
                return this.FaltaField;
            }
            set {
                if ((this.FaltaField.Equals(value) != true)) {
                    this.FaltaField = value;
                    this.RaisePropertyChanged("Falta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fmodificacion {
            get {
                return this.FmodificacionField;
            }
            set {
                if ((this.FmodificacionField.Equals(value) != true)) {
                    this.FmodificacionField = value;
                    this.RaisePropertyChanged("Fmodificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cc {
            get {
                return this.ccField;
            }
            set {
                if ((this.ccField.Equals(value) != true)) {
                    this.ccField = value;
                    this.RaisePropertyChanged("cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cmModalidad {
            get {
                return this.cmModalidadField;
            }
            set {
                if ((this.cmModalidadField.Equals(value) != true)) {
                    this.cmModalidadField = value;
                    this.RaisePropertyChanged("cmModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string csCveSitioAut {
            get {
                return this.csCveSitioAutField;
            }
            set {
                if ((object.ReferenceEquals(this.csCveSitioAutField, value) != true)) {
                    this.csCveSitioAutField = value;
                    this.RaisePropertyChanged("csCveSitioAut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string csCveSitioDef {
            get {
                return this.csCveSitioDefField;
            }
            set {
                if ((object.ReferenceEquals(this.csCveSitioDefField, value) != true)) {
                    this.csCveSitioDefField = value;
                    this.RaisePropertyChanged("csCveSitioDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> csSitio {
            get {
                return this.csSitioField;
            }
            set {
                if ((this.csSitioField.Equals(value) != true)) {
                    this.csSitioField = value;
                    this.RaisePropertyChanged("csSitio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> estRegistro {
            get {
                return this.estRegistroField;
            }
            set {
                if ((this.estRegistroField.Equals(value) != true)) {
                    this.estRegistroField = value;
                    this.RaisePropertyChanged("estRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> iduser {
            get {
                return this.iduserField;
            }
            set {
                if ((this.iduserField.Equals(value) != true)) {
                    this.iduserField = value;
                    this.RaisePropertyChanged("iduser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oeModalidad {
            get {
                return this.oeModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.oeModalidadField, value) != true)) {
                    this.oeModalidadField = value;
                    this.RaisePropertyChanged("oeModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouAdministrador {
            get {
                return this.ouAdministradorField;
            }
            set {
                if ((object.ReferenceEquals(this.ouAdministradorField, value) != true)) {
                    this.ouAdministradorField = value;
                    this.RaisePropertyChanged("ouAdministrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouAgenda {
            get {
                return this.ouAgendaField;
            }
            set {
                if ((object.ReferenceEquals(this.ouAgendaField, value) != true)) {
                    this.ouAgendaField = value;
                    this.RaisePropertyChanged("ouAgenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouApellido1 {
            get {
                return this.ouApellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ouApellido1Field, value) != true)) {
                    this.ouApellido1Field = value;
                    this.RaisePropertyChanged("ouApellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouApellido2 {
            get {
                return this.ouApellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ouApellido2Field, value) != true)) {
                    this.ouApellido2Field = value;
                    this.RaisePropertyChanged("ouApellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouCamMedTra {
            get {
                return this.ouCamMedTraField;
            }
            set {
                if ((object.ReferenceEquals(this.ouCamMedTraField, value) != true)) {
                    this.ouCamMedTraField = value;
                    this.RaisePropertyChanged("ouCamMedTra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouCamion {
            get {
                return this.ouCamionField;
            }
            set {
                if ((object.ReferenceEquals(this.ouCamionField, value) != true)) {
                    this.ouCamionField = value;
                    this.RaisePropertyChanged("ouCamion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouCancelaEstudios {
            get {
                return this.ouCancelaEstudiosField;
            }
            set {
                if ((object.ReferenceEquals(this.ouCancelaEstudiosField, value) != true)) {
                    this.ouCancelaEstudiosField = value;
                    this.RaisePropertyChanged("ouCancelaEstudios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouCatalogo {
            get {
                return this.ouCatalogoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouCatalogoField, value) != true)) {
                    this.ouCatalogoField = value;
                    this.RaisePropertyChanged("ouCatalogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouCedula {
            get {
                return this.ouCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.ouCedulaField, value) != true)) {
                    this.ouCedulaField = value;
                    this.RaisePropertyChanged("ouCedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouComentarios {
            get {
                return this.ouComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ouComentariosField, value) != true)) {
                    this.ouComentariosField = value;
                    this.RaisePropertyChanged("ouComentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouConfirma {
            get {
                return this.ouConfirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.ouConfirmaField, value) != true)) {
                    this.ouConfirmaField = value;
                    this.RaisePropertyChanged("ouConfirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouDictado {
            get {
                return this.ouDictadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouDictadoField, value) != true)) {
                    this.ouDictadoField = value;
                    this.RaisePropertyChanged("ouDictado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouDictadoNewLineMode {
            get {
                return this.ouDictadoNewLineModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ouDictadoNewLineModeField, value) != true)) {
                    this.ouDictadoNewLineModeField = value;
                    this.RaisePropertyChanged("ouDictadoNewLineMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouDireccion {
            get {
                return this.ouDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.ouDireccionField, value) != true)) {
                    this.ouDireccionField = value;
                    this.RaisePropertyChanged("ouDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouEditaEstudio {
            get {
                return this.ouEditaEstudioField;
            }
            set {
                if ((object.ReferenceEquals(this.ouEditaEstudioField, value) != true)) {
                    this.ouEditaEstudioField = value;
                    this.RaisePropertyChanged("ouEditaEstudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouEsRecurso {
            get {
                return this.ouEsRecursoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouEsRecursoField, value) != true)) {
                    this.ouEsRecursoField = value;
                    this.RaisePropertyChanged("ouEsRecurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouEventosUrgencias {
            get {
                return this.ouEventosUrgenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.ouEventosUrgenciasField, value) != true)) {
                    this.ouEventosUrgenciasField = value;
                    this.RaisePropertyChanged("ouEventosUrgencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouFinaliza {
            get {
                return this.ouFinalizaField;
            }
            set {
                if ((object.ReferenceEquals(this.ouFinalizaField, value) != true)) {
                    this.ouFinalizaField = value;
                    this.RaisePropertyChanged("ouFinaliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouFirmaAusencia {
            get {
                return this.ouFirmaAusenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ouFirmaAusenciaField, value) != true)) {
                    this.ouFirmaAusenciaField = value;
                    this.RaisePropertyChanged("ouFirmaAusencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ouFolio {
            get {
                return this.ouFolioField;
            }
            set {
                if ((this.ouFolioField.Equals(value) != true)) {
                    this.ouFolioField = value;
                    this.RaisePropertyChanged("ouFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouGrabador {
            get {
                return this.ouGrabadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ouGrabadorField, value) != true)) {
                    this.ouGrabadorField = value;
                    this.RaisePropertyChanged("ouGrabador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouHOVACamion {
            get {
                return this.ouHOVACamionField;
            }
            set {
                if ((object.ReferenceEquals(this.ouHOVACamionField, value) != true)) {
                    this.ouHOVACamionField = value;
                    this.RaisePropertyChanged("ouHOVACamion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouHistotecnologoA {
            get {
                return this.ouHistotecnologoAField;
            }
            set {
                if ((object.ReferenceEquals(this.ouHistotecnologoAField, value) != true)) {
                    this.ouHistotecnologoAField = value;
                    this.RaisePropertyChanged("ouHistotecnologoA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouHistotecnologoB {
            get {
                return this.ouHistotecnologoBField;
            }
            set {
                if ((object.ReferenceEquals(this.ouHistotecnologoBField, value) != true)) {
                    this.ouHistotecnologoBField = value;
                    this.RaisePropertyChanged("ouHistotecnologoB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouID {
            get {
                return this.ouIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ouIDField, value) != true)) {
                    this.ouIDField = value;
                    this.RaisePropertyChanged("ouID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouIDCard {
            get {
                return this.ouIDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.ouIDCardField, value) != true)) {
                    this.ouIDCardField = value;
                    this.RaisePropertyChanged("ouIDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouIDChecador {
            get {
                return this.ouIDChecadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ouIDChecadorField, value) != true)) {
                    this.ouIDChecadorField = value;
                    this.RaisePropertyChanged("ouIDChecador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouIdHis {
            get {
                return this.ouIdHisField;
            }
            set {
                if ((object.ReferenceEquals(this.ouIdHisField, value) != true)) {
                    this.ouIdHisField = value;
                    this.RaisePropertyChanged("ouIdHis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouIniciales {
            get {
                return this.ouInicialesField;
            }
            set {
                if ((object.ReferenceEquals(this.ouInicialesField, value) != true)) {
                    this.ouInicialesField = value;
                    this.RaisePropertyChanged("ouIniciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouInsertaAddendum {
            get {
                return this.ouInsertaAddendumField;
            }
            set {
                if ((object.ReferenceEquals(this.ouInsertaAddendumField, value) != true)) {
                    this.ouInsertaAddendumField = value;
                    this.RaisePropertyChanged("ouInsertaAddendum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouLiberaEstudios {
            get {
                return this.ouLiberaEstudiosField;
            }
            set {
                if ((object.ReferenceEquals(this.ouLiberaEstudiosField, value) != true)) {
                    this.ouLiberaEstudiosField = value;
                    this.RaisePropertyChanged("ouLiberaEstudios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouListaTrabajo {
            get {
                return this.ouListaTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouListaTrabajoField, value) != true)) {
                    this.ouListaTrabajoField = value;
                    this.RaisePropertyChanged("ouListaTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouLoteGenerado {
            get {
                return this.ouLoteGeneradoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouLoteGeneradoField, value) != true)) {
                    this.ouLoteGeneradoField = value;
                    this.RaisePropertyChanged("ouLoteGenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouMail {
            get {
                return this.ouMailField;
            }
            set {
                if ((object.ReferenceEquals(this.ouMailField, value) != true)) {
                    this.ouMailField = value;
                    this.RaisePropertyChanged("ouMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouMatricula {
            get {
                return this.ouMatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.ouMatriculaField, value) != true)) {
                    this.ouMatriculaField = value;
                    this.RaisePropertyChanged("ouMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouModificaReportes {
            get {
                return this.ouModificaReportesField;
            }
            set {
                if ((object.ReferenceEquals(this.ouModificaReportesField, value) != true)) {
                    this.ouModificaReportesField = value;
                    this.RaisePropertyChanged("ouModificaReportes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNUSA_applicationName {
            get {
                return this.ouNUSA_applicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNUSA_applicationNameField, value) != true)) {
                    this.ouNUSA_applicationNameField = value;
                    this.RaisePropertyChanged("ouNUSA_applicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNUSA_habilitado {
            get {
                return this.ouNUSA_habilitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNUSA_habilitadoField, value) != true)) {
                    this.ouNUSA_habilitadoField = value;
                    this.RaisePropertyChanged("ouNUSA_habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNUSA_language {
            get {
                return this.ouNUSA_languageField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNUSA_languageField, value) != true)) {
                    this.ouNUSA_languageField = value;
                    this.RaisePropertyChanged("ouNUSA_language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNUSA_src {
            get {
                return this.ouNUSA_srcField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNUSA_srcField, value) != true)) {
                    this.ouNUSA_srcField = value;
                    this.RaisePropertyChanged("ouNUSA_src");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNUSA_topic {
            get {
                return this.ouNUSA_topicField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNUSA_topicField, value) != true)) {
                    this.ouNUSA_topicField = value;
                    this.RaisePropertyChanged("ouNUSA_topic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNUSA_userId {
            get {
                return this.ouNUSA_userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNUSA_userIdField, value) != true)) {
                    this.ouNUSA_userIdField = value;
                    this.RaisePropertyChanged("ouNUSA_userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouNombre {
            get {
                return this.ouNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ouNombreField, value) != true)) {
                    this.ouNombreField = value;
                    this.RaisePropertyChanged("ouNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouPacientes {
            get {
                return this.ouPacientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ouPacientesField, value) != true)) {
                    this.ouPacientesField = value;
                    this.RaisePropertyChanged("ouPacientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouPassword {
            get {
                return this.ouPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ouPasswordField, value) != true)) {
                    this.ouPasswordField = value;
                    this.RaisePropertyChanged("ouPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouPatologo {
            get {
                return this.ouPatologoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouPatologoField, value) != true)) {
                    this.ouPatologoField = value;
                    this.RaisePropertyChanged("ouPatologo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouPerfilListaTrabajo {
            get {
                return this.ouPerfilListaTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouPerfilListaTrabajoField, value) != true)) {
                    this.ouPerfilListaTrabajoField = value;
                    this.RaisePropertyChanged("ouPerfilListaTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouReasignaIDPacientes {
            get {
                return this.ouReasignaIDPacientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ouReasignaIDPacientesField, value) != true)) {
                    this.ouReasignaIDPacientesField = value;
                    this.RaisePropertyChanged("ouReasignaIDPacientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouReportes {
            get {
                return this.ouReportesField;
            }
            set {
                if ((object.ReferenceEquals(this.ouReportesField, value) != true)) {
                    this.ouReportesField = value;
                    this.RaisePropertyChanged("ouReportes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouResidente {
            get {
                return this.ouResidenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ouResidenteField, value) != true)) {
                    this.ouResidenteField = value;
                    this.RaisePropertyChanged("ouResidente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouSkin {
            get {
                return this.ouSkinField;
            }
            set {
                if ((object.ReferenceEquals(this.ouSkinField, value) != true)) {
                    this.ouSkinField = value;
                    this.RaisePropertyChanged("ouSkin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouSobreturno {
            get {
                return this.ouSobreturnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouSobreturnoField, value) != true)) {
                    this.ouSobreturnoField = value;
                    this.RaisePropertyChanged("ouSobreturno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouTelefono {
            get {
                return this.ouTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouTelefonoField, value) != true)) {
                    this.ouTelefonoField = value;
                    this.RaisePropertyChanged("ouTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouTelefonoM {
            get {
                return this.ouTelefonoMField;
            }
            set {
                if ((object.ReferenceEquals(this.ouTelefonoMField, value) != true)) {
                    this.ouTelefonoMField = value;
                    this.RaisePropertyChanged("ouTelefonoM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouTelefonoO {
            get {
                return this.ouTelefonoOField;
            }
            set {
                if ((object.ReferenceEquals(this.ouTelefonoOField, value) != true)) {
                    this.ouTelefonoOField = value;
                    this.RaisePropertyChanged("ouTelefonoO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouTipodeDictado {
            get {
                return this.ouTipodeDictadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ouTipodeDictadoField, value) != true)) {
                    this.ouTipodeDictadoField = value;
                    this.RaisePropertyChanged("ouTipodeDictado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouTranscriptor {
            get {
                return this.ouTranscriptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ouTranscriptorField, value) != true)) {
                    this.ouTranscriptorField = value;
                    this.RaisePropertyChanged("ouTranscriptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ouUalta {
            get {
                return this.ouUaltaField;
            }
            set {
                if ((this.ouUaltaField.Equals(value) != true)) {
                    this.ouUaltaField = value;
                    this.RaisePropertyChanged("ouUalta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ouUmodificacion {
            get {
                return this.ouUmodificacionField;
            }
            set {
                if ((this.ouUmodificacionField.Equals(value) != true)) {
                    this.ouUmodificacionField = value;
                    this.RaisePropertyChanged("ouUmodificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouUrgencias {
            get {
                return this.ouUrgenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.ouUrgenciasField, value) != true)) {
                    this.ouUrgenciasField = value;
                    this.RaisePropertyChanged("ouUrgencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ouUsuario {
            get {
                return this.ouUsuarioField;
            }
            set {
                if ((this.ouUsuarioField.Equals(value) != true)) {
                    this.ouUsuarioField = value;
                    this.RaisePropertyChanged("ouUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouVeImagenes {
            get {
                return this.ouVeImagenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ouVeImagenesField, value) != true)) {
                    this.ouVeImagenesField = value;
                    this.RaisePropertyChanged("ouVeImagenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouVocaliIntegracion {
            get {
                return this.ouVocaliIntegracionField;
            }
            set {
                if ((object.ReferenceEquals(this.ouVocaliIntegracionField, value) != true)) {
                    this.ouVocaliIntegracionField = value;
                    this.RaisePropertyChanged("ouVocaliIntegracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouVocaliPassword {
            get {
                return this.ouVocaliPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ouVocaliPasswordField, value) != true)) {
                    this.ouVocaliPasswordField = value;
                    this.RaisePropertyChanged("ouVocaliPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ouVocaliPort {
            get {
                return this.ouVocaliPortField;
            }
            set {
                if ((this.ouVocaliPortField.Equals(value) != true)) {
                    this.ouVocaliPortField = value;
                    this.RaisePropertyChanged("ouVocaliPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouVocaliServer {
            get {
                return this.ouVocaliServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ouVocaliServerField, value) != true)) {
                    this.ouVocaliServerField = value;
                    this.RaisePropertyChanged("ouVocaliServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ouVocaliUSER {
            get {
                return this.ouVocaliUSERField;
            }
            set {
                if ((object.ReferenceEquals(this.ouVocaliUSERField, value) != true)) {
                    this.ouVocaliUSERField = value;
                    this.RaisePropertyChanged("ouVocaliUSER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scValorDefaultEditor {
            get {
                return this.scValorDefaultEditorField;
            }
            set {
                if ((object.ReferenceEquals(this.scValorDefaultEditorField, value) != true)) {
                    this.scValorDefaultEditorField = value;
                    this.RaisePropertyChanged("scValorDefaultEditor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterpretacionService.IInterpretacionService")]
    public interface IInterpretacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterpretacionService/GetData", ReplyAction="http://tempuri.org/IInterpretacionService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterpretacionService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IInterpretacionService/GetDataUsingDataContractResponse")]
        FUJI.InterDF.Site.InterpretacionService.CompositeType GetDataUsingDataContract(FUJI.InterDF.Site.InterpretacionService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterpretacionService/getValidacionProcedeBloqueo", ReplyAction="http://tempuri.org/IInterpretacionService/getValidacionProcedeBloqueoResponse")]
        bool getValidacionProcedeBloqueo(string NumEstudio, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterpretacionService/getInterpretacionList", ReplyAction="http://tempuri.org/IInterpretacionService/getInterpretacionListResponse")]
        System.Collections.Generic.List<FUJI.InterDF.Site.InterpretacionService.vBuscaEnRevision> getInterpretacionList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterpretacionService/getUsuario", ReplyAction="http://tempuri.org/IInterpretacionService/getUsuarioResponse")]
        FUJI.InterDF.Site.InterpretacionService.opeUsuario getUsuario(string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterpretacionServiceChannel : FUJI.InterDF.Site.InterpretacionService.IInterpretacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterpretacionServiceClient : System.ServiceModel.ClientBase<FUJI.InterDF.Site.InterpretacionService.IInterpretacionService>, FUJI.InterDF.Site.InterpretacionService.IInterpretacionService {
        
        public InterpretacionServiceClient() {
        }
        
        public InterpretacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterpretacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterpretacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterpretacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public FUJI.InterDF.Site.InterpretacionService.CompositeType GetDataUsingDataContract(FUJI.InterDF.Site.InterpretacionService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool getValidacionProcedeBloqueo(string NumEstudio, string userID) {
            return base.Channel.getValidacionProcedeBloqueo(NumEstudio, userID);
        }
        
        public System.Collections.Generic.List<FUJI.InterDF.Site.InterpretacionService.vBuscaEnRevision> getInterpretacionList() {
            return base.Channel.getInterpretacionList();
        }
        
        public FUJI.InterDF.Site.InterpretacionService.opeUsuario getUsuario(string user) {
            return base.Channel.getUsuario(user);
        }
    }
}
