#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJIFILM.InterpretacionesDF.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RIS")]
	public partial class dbRiskDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertopeUsuario(opeUsuario instance);
    partial void UpdateopeUsuario(opeUsuario instance);
    partial void DeleteopeUsuario(opeUsuario instance);
    #endregion
		
		public dbRiskDataContext() : 
				base(global::FUJIFILM.InterpretacionesDF.DataAccess.Properties.Settings.Default.RISConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbRiskDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbRiskDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbRiskDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbRiskDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<opeUsuario> opeUsuario
		{
			get
			{
				return this.GetTable<opeUsuario>();
			}
		}
		
		public System.Data.Linq.Table<vBuscaEnRevision> vBuscaEnRevision
		{
			get
			{
				return this.GetTable<vBuscaEnRevision>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spProcedeBloqueo")]
		public ISingleResult<spProcedeBloqueoResult> spProcedeBloqueo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string numeroAcceso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroAcceso, usuarioID);
			return ((ISingleResult<spProcedeBloqueoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.opeUsuario")]
	public partial class opeUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ouUsuario;
		
		private System.Nullable<int> _csSitio;
		
		private System.Nullable<int> _ouFolio;
		
		private string _ouID;
		
		private string _ouNombre;
		
		private string _ouApellido1;
		
		private string _ouApellido2;
		
		private string _ouCedula;
		
		private string _ouMatricula;
		
		private string _ouIDChecador;
		
		private string _ouDireccion;
		
		private string _ouTelefono;
		
		private string _ouTelefonoO;
		
		private string _ouTelefonoM;
		
		private string _ouMail;
		
		private string _ouComentarios;
		
		private string _ouCatalogo;
		
		private string _ouAgenda;
		
		private string _ouConfirma;
		
		private string _ouDictado;
		
		private string _ouReportes;
		
		private string _ouPacientes;
		
		private string _ouAdministrador;
		
		private string _ouEventosUrgencias;
		
		private string _ouSkin;
		
		private System.Nullable<System.DateTime> _Falta;
		
		private System.Nullable<int> _ouUalta;
		
		private System.Nullable<System.DateTime> _Fmodificacion;
		
		private System.Nullable<int> _ouUmodificacion;
		
		private System.Nullable<bool> _estRegistro;
		
		private System.Nullable<int> _cc;
		
		private string _ouUrgencias;
		
		private string _ouSobreturno;
		
		private string _ouListaTrabajo;
		
		private string _ouFinaliza;
		
		private string _ouCamMedTra;
		
		private string _ouPatologo;
		
		private string _ouHistotecnologoA;
		
		private string _ouHistotecnologoB;
		
		private string _ouResidente;
		
		private string _ouLiberaEstudios;
		
		private string _ouTranscriptor;
		
		private string _ouGrabador;
		
		private string _ouVeImagenes;
		
		private string _ouIniciales;
		
		private string _ouPassword;
		
		private string _ouIDCard;
		
		private string _ouLoteGenerado;
		
		private string _ouModificaReportes;
		
		private string _ouPerfilListaTrabajo;
		
		private string _ouInsertaAddendum;
		
		private System.Nullable<int> _cmModalidad;
		
		private string _ouReasignaIDPacientes;
		
		private string _ouTipodeDictado;
		
		private string _ouCancelaEstudios;
		
		private System.Nullable<int> _iduser;
		
		private string _ouEditaEstudio;
		
		private string _ouIdHis;
		
		private string _ouFirmaAusencia;
		
		private string _ouCamion;
		
		private string _ouHOVACamion;
		
		private string _csCveSitioAut;
		
		private string _csCveSitioDef;
		
		private string _ouNUSA_userId;
		
		private string _ouNUSA_applicationName;
		
		private string _ouNUSA_language;
		
		private string _ouNUSA_topic;
		
		private string _ouNUSA_src;
		
		private string _ouNUSA_habilitado;
		
		private string _ouEsRecurso;
		
		private string _ouDictadoNewLineMode;
		
		private string _ouVocaliUSER;
		
		private string _ouVocaliPassword;
		
		private string _ouVocaliServer;
		
		private System.Nullable<int> _ouVocaliPort;
		
		private string _ouVocaliIntegracion;
		
		private string _scValorDefaultEditor;
		
		private string _oeModalidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnouUsuarioChanging(int value);
    partial void OnouUsuarioChanged();
    partial void OncsSitioChanging(System.Nullable<int> value);
    partial void OncsSitioChanged();
    partial void OnouFolioChanging(System.Nullable<int> value);
    partial void OnouFolioChanged();
    partial void OnouIDChanging(string value);
    partial void OnouIDChanged();
    partial void OnouNombreChanging(string value);
    partial void OnouNombreChanged();
    partial void OnouApellido1Changing(string value);
    partial void OnouApellido1Changed();
    partial void OnouApellido2Changing(string value);
    partial void OnouApellido2Changed();
    partial void OnouCedulaChanging(string value);
    partial void OnouCedulaChanged();
    partial void OnouMatriculaChanging(string value);
    partial void OnouMatriculaChanged();
    partial void OnouIDChecadorChanging(string value);
    partial void OnouIDChecadorChanged();
    partial void OnouDireccionChanging(string value);
    partial void OnouDireccionChanged();
    partial void OnouTelefonoChanging(string value);
    partial void OnouTelefonoChanged();
    partial void OnouTelefonoOChanging(string value);
    partial void OnouTelefonoOChanged();
    partial void OnouTelefonoMChanging(string value);
    partial void OnouTelefonoMChanged();
    partial void OnouMailChanging(string value);
    partial void OnouMailChanged();
    partial void OnouComentariosChanging(string value);
    partial void OnouComentariosChanged();
    partial void OnouCatalogoChanging(string value);
    partial void OnouCatalogoChanged();
    partial void OnouAgendaChanging(string value);
    partial void OnouAgendaChanged();
    partial void OnouConfirmaChanging(string value);
    partial void OnouConfirmaChanged();
    partial void OnouDictadoChanging(string value);
    partial void OnouDictadoChanged();
    partial void OnouReportesChanging(string value);
    partial void OnouReportesChanged();
    partial void OnouPacientesChanging(string value);
    partial void OnouPacientesChanged();
    partial void OnouAdministradorChanging(string value);
    partial void OnouAdministradorChanged();
    partial void OnouEventosUrgenciasChanging(string value);
    partial void OnouEventosUrgenciasChanged();
    partial void OnouSkinChanging(string value);
    partial void OnouSkinChanged();
    partial void OnFaltaChanging(System.Nullable<System.DateTime> value);
    partial void OnFaltaChanged();
    partial void OnouUaltaChanging(System.Nullable<int> value);
    partial void OnouUaltaChanged();
    partial void OnFmodificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFmodificacionChanged();
    partial void OnouUmodificacionChanging(System.Nullable<int> value);
    partial void OnouUmodificacionChanged();
    partial void OnestRegistroChanging(System.Nullable<bool> value);
    partial void OnestRegistroChanged();
    partial void OnccChanging(System.Nullable<int> value);
    partial void OnccChanged();
    partial void OnouUrgenciasChanging(string value);
    partial void OnouUrgenciasChanged();
    partial void OnouSobreturnoChanging(string value);
    partial void OnouSobreturnoChanged();
    partial void OnouListaTrabajoChanging(string value);
    partial void OnouListaTrabajoChanged();
    partial void OnouFinalizaChanging(string value);
    partial void OnouFinalizaChanged();
    partial void OnouCamMedTraChanging(string value);
    partial void OnouCamMedTraChanged();
    partial void OnouPatologoChanging(string value);
    partial void OnouPatologoChanged();
    partial void OnouHistotecnologoAChanging(string value);
    partial void OnouHistotecnologoAChanged();
    partial void OnouHistotecnologoBChanging(string value);
    partial void OnouHistotecnologoBChanged();
    partial void OnouResidenteChanging(string value);
    partial void OnouResidenteChanged();
    partial void OnouLiberaEstudiosChanging(string value);
    partial void OnouLiberaEstudiosChanged();
    partial void OnouTranscriptorChanging(string value);
    partial void OnouTranscriptorChanged();
    partial void OnouGrabadorChanging(string value);
    partial void OnouGrabadorChanged();
    partial void OnouVeImagenesChanging(string value);
    partial void OnouVeImagenesChanged();
    partial void OnouInicialesChanging(string value);
    partial void OnouInicialesChanged();
    partial void OnouPasswordChanging(string value);
    partial void OnouPasswordChanged();
    partial void OnouIDCardChanging(string value);
    partial void OnouIDCardChanged();
    partial void OnouLoteGeneradoChanging(string value);
    partial void OnouLoteGeneradoChanged();
    partial void OnouModificaReportesChanging(string value);
    partial void OnouModificaReportesChanged();
    partial void OnouPerfilListaTrabajoChanging(string value);
    partial void OnouPerfilListaTrabajoChanged();
    partial void OnouInsertaAddendumChanging(string value);
    partial void OnouInsertaAddendumChanged();
    partial void OncmModalidadChanging(System.Nullable<int> value);
    partial void OncmModalidadChanged();
    partial void OnouReasignaIDPacientesChanging(string value);
    partial void OnouReasignaIDPacientesChanged();
    partial void OnouTipodeDictadoChanging(string value);
    partial void OnouTipodeDictadoChanged();
    partial void OnouCancelaEstudiosChanging(string value);
    partial void OnouCancelaEstudiosChanged();
    partial void OniduserChanging(System.Nullable<int> value);
    partial void OniduserChanged();
    partial void OnouEditaEstudioChanging(string value);
    partial void OnouEditaEstudioChanged();
    partial void OnouIdHisChanging(string value);
    partial void OnouIdHisChanged();
    partial void OnouFirmaAusenciaChanging(string value);
    partial void OnouFirmaAusenciaChanged();
    partial void OnouCamionChanging(string value);
    partial void OnouCamionChanged();
    partial void OnouHOVACamionChanging(string value);
    partial void OnouHOVACamionChanged();
    partial void OncsCveSitioAutChanging(string value);
    partial void OncsCveSitioAutChanged();
    partial void OncsCveSitioDefChanging(string value);
    partial void OncsCveSitioDefChanged();
    partial void OnouNUSA_userIdChanging(string value);
    partial void OnouNUSA_userIdChanged();
    partial void OnouNUSA_applicationNameChanging(string value);
    partial void OnouNUSA_applicationNameChanged();
    partial void OnouNUSA_languageChanging(string value);
    partial void OnouNUSA_languageChanged();
    partial void OnouNUSA_topicChanging(string value);
    partial void OnouNUSA_topicChanged();
    partial void OnouNUSA_srcChanging(string value);
    partial void OnouNUSA_srcChanged();
    partial void OnouNUSA_habilitadoChanging(string value);
    partial void OnouNUSA_habilitadoChanged();
    partial void OnouEsRecursoChanging(string value);
    partial void OnouEsRecursoChanged();
    partial void OnouDictadoNewLineModeChanging(string value);
    partial void OnouDictadoNewLineModeChanged();
    partial void OnouVocaliUSERChanging(string value);
    partial void OnouVocaliUSERChanged();
    partial void OnouVocaliPasswordChanging(string value);
    partial void OnouVocaliPasswordChanged();
    partial void OnouVocaliServerChanging(string value);
    partial void OnouVocaliServerChanged();
    partial void OnouVocaliPortChanging(System.Nullable<int> value);
    partial void OnouVocaliPortChanged();
    partial void OnouVocaliIntegracionChanging(string value);
    partial void OnouVocaliIntegracionChanged();
    partial void OnscValorDefaultEditorChanging(string value);
    partial void OnscValorDefaultEditorChanged();
    partial void OnoeModalidadChanging(string value);
    partial void OnoeModalidadChanged();
    #endregion
		
		public opeUsuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ouUsuario
		{
			get
			{
				return this._ouUsuario;
			}
			set
			{
				if ((this._ouUsuario != value))
				{
					this.OnouUsuarioChanging(value);
					this.SendPropertyChanging();
					this._ouUsuario = value;
					this.SendPropertyChanged("ouUsuario");
					this.OnouUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_csSitio", DbType="Int")]
		public System.Nullable<int> csSitio
		{
			get
			{
				return this._csSitio;
			}
			set
			{
				if ((this._csSitio != value))
				{
					this.OncsSitioChanging(value);
					this.SendPropertyChanging();
					this._csSitio = value;
					this.SendPropertyChanged("csSitio");
					this.OncsSitioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouFolio", DbType="Int")]
		public System.Nullable<int> ouFolio
		{
			get
			{
				return this._ouFolio;
			}
			set
			{
				if ((this._ouFolio != value))
				{
					this.OnouFolioChanging(value);
					this.SendPropertyChanging();
					this._ouFolio = value;
					this.SendPropertyChanged("ouFolio");
					this.OnouFolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouID", DbType="NVarChar(50)")]
		public string ouID
		{
			get
			{
				return this._ouID;
			}
			set
			{
				if ((this._ouID != value))
				{
					this.OnouIDChanging(value);
					this.SendPropertyChanging();
					this._ouID = value;
					this.SendPropertyChanged("ouID");
					this.OnouIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNombre", DbType="NVarChar(150)")]
		public string ouNombre
		{
			get
			{
				return this._ouNombre;
			}
			set
			{
				if ((this._ouNombre != value))
				{
					this.OnouNombreChanging(value);
					this.SendPropertyChanging();
					this._ouNombre = value;
					this.SendPropertyChanged("ouNombre");
					this.OnouNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouApellido1", DbType="NVarChar(150)")]
		public string ouApellido1
		{
			get
			{
				return this._ouApellido1;
			}
			set
			{
				if ((this._ouApellido1 != value))
				{
					this.OnouApellido1Changing(value);
					this.SendPropertyChanging();
					this._ouApellido1 = value;
					this.SendPropertyChanged("ouApellido1");
					this.OnouApellido1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouApellido2", DbType="NVarChar(150)")]
		public string ouApellido2
		{
			get
			{
				return this._ouApellido2;
			}
			set
			{
				if ((this._ouApellido2 != value))
				{
					this.OnouApellido2Changing(value);
					this.SendPropertyChanging();
					this._ouApellido2 = value;
					this.SendPropertyChanged("ouApellido2");
					this.OnouApellido2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouCedula", DbType="NVarChar(250)")]
		public string ouCedula
		{
			get
			{
				return this._ouCedula;
			}
			set
			{
				if ((this._ouCedula != value))
				{
					this.OnouCedulaChanging(value);
					this.SendPropertyChanging();
					this._ouCedula = value;
					this.SendPropertyChanged("ouCedula");
					this.OnouCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouMatricula", DbType="NVarChar(255)")]
		public string ouMatricula
		{
			get
			{
				return this._ouMatricula;
			}
			set
			{
				if ((this._ouMatricula != value))
				{
					this.OnouMatriculaChanging(value);
					this.SendPropertyChanging();
					this._ouMatricula = value;
					this.SendPropertyChanged("ouMatricula");
					this.OnouMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouIDChecador", DbType="NChar(30)")]
		public string ouIDChecador
		{
			get
			{
				return this._ouIDChecador;
			}
			set
			{
				if ((this._ouIDChecador != value))
				{
					this.OnouIDChecadorChanging(value);
					this.SendPropertyChanging();
					this._ouIDChecador = value;
					this.SendPropertyChanged("ouIDChecador");
					this.OnouIDChecadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouDireccion", DbType="NVarChar(150)")]
		public string ouDireccion
		{
			get
			{
				return this._ouDireccion;
			}
			set
			{
				if ((this._ouDireccion != value))
				{
					this.OnouDireccionChanging(value);
					this.SendPropertyChanging();
					this._ouDireccion = value;
					this.SendPropertyChanged("ouDireccion");
					this.OnouDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouTelefono", DbType="NVarChar(20)")]
		public string ouTelefono
		{
			get
			{
				return this._ouTelefono;
			}
			set
			{
				if ((this._ouTelefono != value))
				{
					this.OnouTelefonoChanging(value);
					this.SendPropertyChanging();
					this._ouTelefono = value;
					this.SendPropertyChanged("ouTelefono");
					this.OnouTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouTelefonoO", DbType="NVarChar(20)")]
		public string ouTelefonoO
		{
			get
			{
				return this._ouTelefonoO;
			}
			set
			{
				if ((this._ouTelefonoO != value))
				{
					this.OnouTelefonoOChanging(value);
					this.SendPropertyChanging();
					this._ouTelefonoO = value;
					this.SendPropertyChanged("ouTelefonoO");
					this.OnouTelefonoOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouTelefonoM", DbType="NVarChar(20)")]
		public string ouTelefonoM
		{
			get
			{
				return this._ouTelefonoM;
			}
			set
			{
				if ((this._ouTelefonoM != value))
				{
					this.OnouTelefonoMChanging(value);
					this.SendPropertyChanging();
					this._ouTelefonoM = value;
					this.SendPropertyChanged("ouTelefonoM");
					this.OnouTelefonoMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouMail", DbType="NVarChar(100)")]
		public string ouMail
		{
			get
			{
				return this._ouMail;
			}
			set
			{
				if ((this._ouMail != value))
				{
					this.OnouMailChanging(value);
					this.SendPropertyChanging();
					this._ouMail = value;
					this.SendPropertyChanged("ouMail");
					this.OnouMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouComentarios", DbType="NVarChar(MAX)")]
		public string ouComentarios
		{
			get
			{
				return this._ouComentarios;
			}
			set
			{
				if ((this._ouComentarios != value))
				{
					this.OnouComentariosChanging(value);
					this.SendPropertyChanging();
					this._ouComentarios = value;
					this.SendPropertyChanged("ouComentarios");
					this.OnouComentariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouCatalogo", DbType="NVarChar(1)")]
		public string ouCatalogo
		{
			get
			{
				return this._ouCatalogo;
			}
			set
			{
				if ((this._ouCatalogo != value))
				{
					this.OnouCatalogoChanging(value);
					this.SendPropertyChanging();
					this._ouCatalogo = value;
					this.SendPropertyChanged("ouCatalogo");
					this.OnouCatalogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouAgenda", DbType="NVarChar(1)")]
		public string ouAgenda
		{
			get
			{
				return this._ouAgenda;
			}
			set
			{
				if ((this._ouAgenda != value))
				{
					this.OnouAgendaChanging(value);
					this.SendPropertyChanging();
					this._ouAgenda = value;
					this.SendPropertyChanged("ouAgenda");
					this.OnouAgendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouConfirma", DbType="NVarChar(1)")]
		public string ouConfirma
		{
			get
			{
				return this._ouConfirma;
			}
			set
			{
				if ((this._ouConfirma != value))
				{
					this.OnouConfirmaChanging(value);
					this.SendPropertyChanging();
					this._ouConfirma = value;
					this.SendPropertyChanged("ouConfirma");
					this.OnouConfirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouDictado", DbType="NVarChar(1)")]
		public string ouDictado
		{
			get
			{
				return this._ouDictado;
			}
			set
			{
				if ((this._ouDictado != value))
				{
					this.OnouDictadoChanging(value);
					this.SendPropertyChanging();
					this._ouDictado = value;
					this.SendPropertyChanged("ouDictado");
					this.OnouDictadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouReportes", DbType="NVarChar(1)")]
		public string ouReportes
		{
			get
			{
				return this._ouReportes;
			}
			set
			{
				if ((this._ouReportes != value))
				{
					this.OnouReportesChanging(value);
					this.SendPropertyChanging();
					this._ouReportes = value;
					this.SendPropertyChanged("ouReportes");
					this.OnouReportesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouPacientes", DbType="NVarChar(1)")]
		public string ouPacientes
		{
			get
			{
				return this._ouPacientes;
			}
			set
			{
				if ((this._ouPacientes != value))
				{
					this.OnouPacientesChanging(value);
					this.SendPropertyChanging();
					this._ouPacientes = value;
					this.SendPropertyChanged("ouPacientes");
					this.OnouPacientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouAdministrador", DbType="NVarChar(1)")]
		public string ouAdministrador
		{
			get
			{
				return this._ouAdministrador;
			}
			set
			{
				if ((this._ouAdministrador != value))
				{
					this.OnouAdministradorChanging(value);
					this.SendPropertyChanging();
					this._ouAdministrador = value;
					this.SendPropertyChanged("ouAdministrador");
					this.OnouAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouEventosUrgencias", DbType="NVarChar(1)")]
		public string ouEventosUrgencias
		{
			get
			{
				return this._ouEventosUrgencias;
			}
			set
			{
				if ((this._ouEventosUrgencias != value))
				{
					this.OnouEventosUrgenciasChanging(value);
					this.SendPropertyChanging();
					this._ouEventosUrgencias = value;
					this.SendPropertyChanged("ouEventosUrgencias");
					this.OnouEventosUrgenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouSkin", DbType="NVarChar(20)")]
		public string ouSkin
		{
			get
			{
				return this._ouSkin;
			}
			set
			{
				if ((this._ouSkin != value))
				{
					this.OnouSkinChanging(value);
					this.SendPropertyChanging();
					this._ouSkin = value;
					this.SendPropertyChanged("ouSkin");
					this.OnouSkinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Falta", DbType="DateTime")]
		public System.Nullable<System.DateTime> Falta
		{
			get
			{
				return this._Falta;
			}
			set
			{
				if ((this._Falta != value))
				{
					this.OnFaltaChanging(value);
					this.SendPropertyChanging();
					this._Falta = value;
					this.SendPropertyChanged("Falta");
					this.OnFaltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouUalta", DbType="Int")]
		public System.Nullable<int> ouUalta
		{
			get
			{
				return this._ouUalta;
			}
			set
			{
				if ((this._ouUalta != value))
				{
					this.OnouUaltaChanging(value);
					this.SendPropertyChanging();
					this._ouUalta = value;
					this.SendPropertyChanged("ouUalta");
					this.OnouUaltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fmodificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fmodificacion
		{
			get
			{
				return this._Fmodificacion;
			}
			set
			{
				if ((this._Fmodificacion != value))
				{
					this.OnFmodificacionChanging(value);
					this.SendPropertyChanging();
					this._Fmodificacion = value;
					this.SendPropertyChanged("Fmodificacion");
					this.OnFmodificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouUmodificacion", DbType="Int")]
		public System.Nullable<int> ouUmodificacion
		{
			get
			{
				return this._ouUmodificacion;
			}
			set
			{
				if ((this._ouUmodificacion != value))
				{
					this.OnouUmodificacionChanging(value);
					this.SendPropertyChanging();
					this._ouUmodificacion = value;
					this.SendPropertyChanged("ouUmodificacion");
					this.OnouUmodificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estRegistro", DbType="Bit")]
		public System.Nullable<bool> estRegistro
		{
			get
			{
				return this._estRegistro;
			}
			set
			{
				if ((this._estRegistro != value))
				{
					this.OnestRegistroChanging(value);
					this.SendPropertyChanging();
					this._estRegistro = value;
					this.SendPropertyChanged("estRegistro");
					this.OnestRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cc", DbType="Int")]
		public System.Nullable<int> cc
		{
			get
			{
				return this._cc;
			}
			set
			{
				if ((this._cc != value))
				{
					this.OnccChanging(value);
					this.SendPropertyChanging();
					this._cc = value;
					this.SendPropertyChanged("cc");
					this.OnccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouUrgencias", DbType="NVarChar(1)")]
		public string ouUrgencias
		{
			get
			{
				return this._ouUrgencias;
			}
			set
			{
				if ((this._ouUrgencias != value))
				{
					this.OnouUrgenciasChanging(value);
					this.SendPropertyChanging();
					this._ouUrgencias = value;
					this.SendPropertyChanged("ouUrgencias");
					this.OnouUrgenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouSobreturno", DbType="NVarChar(1)")]
		public string ouSobreturno
		{
			get
			{
				return this._ouSobreturno;
			}
			set
			{
				if ((this._ouSobreturno != value))
				{
					this.OnouSobreturnoChanging(value);
					this.SendPropertyChanging();
					this._ouSobreturno = value;
					this.SendPropertyChanged("ouSobreturno");
					this.OnouSobreturnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouListaTrabajo", DbType="NVarChar(1)")]
		public string ouListaTrabajo
		{
			get
			{
				return this._ouListaTrabajo;
			}
			set
			{
				if ((this._ouListaTrabajo != value))
				{
					this.OnouListaTrabajoChanging(value);
					this.SendPropertyChanging();
					this._ouListaTrabajo = value;
					this.SendPropertyChanged("ouListaTrabajo");
					this.OnouListaTrabajoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouFinaliza", DbType="NVarChar(1)")]
		public string ouFinaliza
		{
			get
			{
				return this._ouFinaliza;
			}
			set
			{
				if ((this._ouFinaliza != value))
				{
					this.OnouFinalizaChanging(value);
					this.SendPropertyChanging();
					this._ouFinaliza = value;
					this.SendPropertyChanged("ouFinaliza");
					this.OnouFinalizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouCamMedTra", DbType="NVarChar(1)")]
		public string ouCamMedTra
		{
			get
			{
				return this._ouCamMedTra;
			}
			set
			{
				if ((this._ouCamMedTra != value))
				{
					this.OnouCamMedTraChanging(value);
					this.SendPropertyChanging();
					this._ouCamMedTra = value;
					this.SendPropertyChanged("ouCamMedTra");
					this.OnouCamMedTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouPatologo", DbType="NVarChar(1)")]
		public string ouPatologo
		{
			get
			{
				return this._ouPatologo;
			}
			set
			{
				if ((this._ouPatologo != value))
				{
					this.OnouPatologoChanging(value);
					this.SendPropertyChanging();
					this._ouPatologo = value;
					this.SendPropertyChanged("ouPatologo");
					this.OnouPatologoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouHistotecnologoA", DbType="NVarChar(1)")]
		public string ouHistotecnologoA
		{
			get
			{
				return this._ouHistotecnologoA;
			}
			set
			{
				if ((this._ouHistotecnologoA != value))
				{
					this.OnouHistotecnologoAChanging(value);
					this.SendPropertyChanging();
					this._ouHistotecnologoA = value;
					this.SendPropertyChanged("ouHistotecnologoA");
					this.OnouHistotecnologoAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouHistotecnologoB", DbType="NVarChar(1)")]
		public string ouHistotecnologoB
		{
			get
			{
				return this._ouHistotecnologoB;
			}
			set
			{
				if ((this._ouHistotecnologoB != value))
				{
					this.OnouHistotecnologoBChanging(value);
					this.SendPropertyChanging();
					this._ouHistotecnologoB = value;
					this.SendPropertyChanged("ouHistotecnologoB");
					this.OnouHistotecnologoBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouResidente", DbType="NVarChar(1)")]
		public string ouResidente
		{
			get
			{
				return this._ouResidente;
			}
			set
			{
				if ((this._ouResidente != value))
				{
					this.OnouResidenteChanging(value);
					this.SendPropertyChanging();
					this._ouResidente = value;
					this.SendPropertyChanged("ouResidente");
					this.OnouResidenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouLiberaEstudios", DbType="NVarChar(1)")]
		public string ouLiberaEstudios
		{
			get
			{
				return this._ouLiberaEstudios;
			}
			set
			{
				if ((this._ouLiberaEstudios != value))
				{
					this.OnouLiberaEstudiosChanging(value);
					this.SendPropertyChanging();
					this._ouLiberaEstudios = value;
					this.SendPropertyChanged("ouLiberaEstudios");
					this.OnouLiberaEstudiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouTranscriptor", DbType="NVarChar(1)")]
		public string ouTranscriptor
		{
			get
			{
				return this._ouTranscriptor;
			}
			set
			{
				if ((this._ouTranscriptor != value))
				{
					this.OnouTranscriptorChanging(value);
					this.SendPropertyChanging();
					this._ouTranscriptor = value;
					this.SendPropertyChanged("ouTranscriptor");
					this.OnouTranscriptorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouGrabador", DbType="NVarChar(1)")]
		public string ouGrabador
		{
			get
			{
				return this._ouGrabador;
			}
			set
			{
				if ((this._ouGrabador != value))
				{
					this.OnouGrabadorChanging(value);
					this.SendPropertyChanging();
					this._ouGrabador = value;
					this.SendPropertyChanged("ouGrabador");
					this.OnouGrabadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouVeImagenes", DbType="NVarChar(1)")]
		public string ouVeImagenes
		{
			get
			{
				return this._ouVeImagenes;
			}
			set
			{
				if ((this._ouVeImagenes != value))
				{
					this.OnouVeImagenesChanging(value);
					this.SendPropertyChanging();
					this._ouVeImagenes = value;
					this.SendPropertyChanged("ouVeImagenes");
					this.OnouVeImagenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouIniciales", DbType="NVarChar(10)")]
		public string ouIniciales
		{
			get
			{
				return this._ouIniciales;
			}
			set
			{
				if ((this._ouIniciales != value))
				{
					this.OnouInicialesChanging(value);
					this.SendPropertyChanging();
					this._ouIniciales = value;
					this.SendPropertyChanged("ouIniciales");
					this.OnouInicialesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouPassword", DbType="NVarChar(16)")]
		public string ouPassword
		{
			get
			{
				return this._ouPassword;
			}
			set
			{
				if ((this._ouPassword != value))
				{
					this.OnouPasswordChanging(value);
					this.SendPropertyChanging();
					this._ouPassword = value;
					this.SendPropertyChanged("ouPassword");
					this.OnouPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouIDCard", DbType="NVarChar(20)")]
		public string ouIDCard
		{
			get
			{
				return this._ouIDCard;
			}
			set
			{
				if ((this._ouIDCard != value))
				{
					this.OnouIDCardChanging(value);
					this.SendPropertyChanging();
					this._ouIDCard = value;
					this.SendPropertyChanged("ouIDCard");
					this.OnouIDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouLoteGenerado", DbType="NVarChar(30)")]
		public string ouLoteGenerado
		{
			get
			{
				return this._ouLoteGenerado;
			}
			set
			{
				if ((this._ouLoteGenerado != value))
				{
					this.OnouLoteGeneradoChanging(value);
					this.SendPropertyChanging();
					this._ouLoteGenerado = value;
					this.SendPropertyChanged("ouLoteGenerado");
					this.OnouLoteGeneradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouModificaReportes", DbType="NVarChar(1)")]
		public string ouModificaReportes
		{
			get
			{
				return this._ouModificaReportes;
			}
			set
			{
				if ((this._ouModificaReportes != value))
				{
					this.OnouModificaReportesChanging(value);
					this.SendPropertyChanging();
					this._ouModificaReportes = value;
					this.SendPropertyChanged("ouModificaReportes");
					this.OnouModificaReportesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouPerfilListaTrabajo", DbType="NVarChar(1)")]
		public string ouPerfilListaTrabajo
		{
			get
			{
				return this._ouPerfilListaTrabajo;
			}
			set
			{
				if ((this._ouPerfilListaTrabajo != value))
				{
					this.OnouPerfilListaTrabajoChanging(value);
					this.SendPropertyChanging();
					this._ouPerfilListaTrabajo = value;
					this.SendPropertyChanged("ouPerfilListaTrabajo");
					this.OnouPerfilListaTrabajoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouInsertaAddendum", DbType="NVarChar(1)")]
		public string ouInsertaAddendum
		{
			get
			{
				return this._ouInsertaAddendum;
			}
			set
			{
				if ((this._ouInsertaAddendum != value))
				{
					this.OnouInsertaAddendumChanging(value);
					this.SendPropertyChanging();
					this._ouInsertaAddendum = value;
					this.SendPropertyChanged("ouInsertaAddendum");
					this.OnouInsertaAddendumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmModalidad", DbType="Int")]
		public System.Nullable<int> cmModalidad
		{
			get
			{
				return this._cmModalidad;
			}
			set
			{
				if ((this._cmModalidad != value))
				{
					this.OncmModalidadChanging(value);
					this.SendPropertyChanging();
					this._cmModalidad = value;
					this.SendPropertyChanged("cmModalidad");
					this.OncmModalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouReasignaIDPacientes", DbType="NVarChar(1)")]
		public string ouReasignaIDPacientes
		{
			get
			{
				return this._ouReasignaIDPacientes;
			}
			set
			{
				if ((this._ouReasignaIDPacientes != value))
				{
					this.OnouReasignaIDPacientesChanging(value);
					this.SendPropertyChanging();
					this._ouReasignaIDPacientes = value;
					this.SendPropertyChanged("ouReasignaIDPacientes");
					this.OnouReasignaIDPacientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouTipodeDictado", DbType="NVarChar(1)")]
		public string ouTipodeDictado
		{
			get
			{
				return this._ouTipodeDictado;
			}
			set
			{
				if ((this._ouTipodeDictado != value))
				{
					this.OnouTipodeDictadoChanging(value);
					this.SendPropertyChanging();
					this._ouTipodeDictado = value;
					this.SendPropertyChanged("ouTipodeDictado");
					this.OnouTipodeDictadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouCancelaEstudios", DbType="NVarChar(1)")]
		public string ouCancelaEstudios
		{
			get
			{
				return this._ouCancelaEstudios;
			}
			set
			{
				if ((this._ouCancelaEstudios != value))
				{
					this.OnouCancelaEstudiosChanging(value);
					this.SendPropertyChanging();
					this._ouCancelaEstudios = value;
					this.SendPropertyChanged("ouCancelaEstudios");
					this.OnouCancelaEstudiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iduser", DbType="Int")]
		public System.Nullable<int> iduser
		{
			get
			{
				return this._iduser;
			}
			set
			{
				if ((this._iduser != value))
				{
					this.OniduserChanging(value);
					this.SendPropertyChanging();
					this._iduser = value;
					this.SendPropertyChanged("iduser");
					this.OniduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouEditaEstudio", DbType="NVarChar(1)")]
		public string ouEditaEstudio
		{
			get
			{
				return this._ouEditaEstudio;
			}
			set
			{
				if ((this._ouEditaEstudio != value))
				{
					this.OnouEditaEstudioChanging(value);
					this.SendPropertyChanging();
					this._ouEditaEstudio = value;
					this.SendPropertyChanged("ouEditaEstudio");
					this.OnouEditaEstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouIdHis", DbType="NVarChar(20)")]
		public string ouIdHis
		{
			get
			{
				return this._ouIdHis;
			}
			set
			{
				if ((this._ouIdHis != value))
				{
					this.OnouIdHisChanging(value);
					this.SendPropertyChanging();
					this._ouIdHis = value;
					this.SendPropertyChanged("ouIdHis");
					this.OnouIdHisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouFirmaAusencia", DbType="NVarChar(1)")]
		public string ouFirmaAusencia
		{
			get
			{
				return this._ouFirmaAusencia;
			}
			set
			{
				if ((this._ouFirmaAusencia != value))
				{
					this.OnouFirmaAusenciaChanging(value);
					this.SendPropertyChanging();
					this._ouFirmaAusencia = value;
					this.SendPropertyChanged("ouFirmaAusencia");
					this.OnouFirmaAusenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouCamion", DbType="NVarChar(30)")]
		public string ouCamion
		{
			get
			{
				return this._ouCamion;
			}
			set
			{
				if ((this._ouCamion != value))
				{
					this.OnouCamionChanging(value);
					this.SendPropertyChanging();
					this._ouCamion = value;
					this.SendPropertyChanged("ouCamion");
					this.OnouCamionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouHOVACamion", DbType="NVarChar(30)")]
		public string ouHOVACamion
		{
			get
			{
				return this._ouHOVACamion;
			}
			set
			{
				if ((this._ouHOVACamion != value))
				{
					this.OnouHOVACamionChanging(value);
					this.SendPropertyChanging();
					this._ouHOVACamion = value;
					this.SendPropertyChanged("ouHOVACamion");
					this.OnouHOVACamionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_csCveSitioAut", DbType="NVarChar(255)")]
		public string csCveSitioAut
		{
			get
			{
				return this._csCveSitioAut;
			}
			set
			{
				if ((this._csCveSitioAut != value))
				{
					this.OncsCveSitioAutChanging(value);
					this.SendPropertyChanging();
					this._csCveSitioAut = value;
					this.SendPropertyChanged("csCveSitioAut");
					this.OncsCveSitioAutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_csCveSitioDef", DbType="NVarChar(10)")]
		public string csCveSitioDef
		{
			get
			{
				return this._csCveSitioDef;
			}
			set
			{
				if ((this._csCveSitioDef != value))
				{
					this.OncsCveSitioDefChanging(value);
					this.SendPropertyChanging();
					this._csCveSitioDef = value;
					this.SendPropertyChanged("csCveSitioDef");
					this.OncsCveSitioDefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNUSA_userId", DbType="NVarChar(50)")]
		public string ouNUSA_userId
		{
			get
			{
				return this._ouNUSA_userId;
			}
			set
			{
				if ((this._ouNUSA_userId != value))
				{
					this.OnouNUSA_userIdChanging(value);
					this.SendPropertyChanging();
					this._ouNUSA_userId = value;
					this.SendPropertyChanged("ouNUSA_userId");
					this.OnouNUSA_userIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNUSA_applicationName", DbType="NVarChar(50)")]
		public string ouNUSA_applicationName
		{
			get
			{
				return this._ouNUSA_applicationName;
			}
			set
			{
				if ((this._ouNUSA_applicationName != value))
				{
					this.OnouNUSA_applicationNameChanging(value);
					this.SendPropertyChanging();
					this._ouNUSA_applicationName = value;
					this.SendPropertyChanged("ouNUSA_applicationName");
					this.OnouNUSA_applicationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNUSA_language", DbType="NVarChar(50)")]
		public string ouNUSA_language
		{
			get
			{
				return this._ouNUSA_language;
			}
			set
			{
				if ((this._ouNUSA_language != value))
				{
					this.OnouNUSA_languageChanging(value);
					this.SendPropertyChanging();
					this._ouNUSA_language = value;
					this.SendPropertyChanged("ouNUSA_language");
					this.OnouNUSA_languageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNUSA_topic", DbType="NVarChar(50)")]
		public string ouNUSA_topic
		{
			get
			{
				return this._ouNUSA_topic;
			}
			set
			{
				if ((this._ouNUSA_topic != value))
				{
					this.OnouNUSA_topicChanging(value);
					this.SendPropertyChanging();
					this._ouNUSA_topic = value;
					this.SendPropertyChanged("ouNUSA_topic");
					this.OnouNUSA_topicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNUSA_src", DbType="NVarChar(MAX)")]
		public string ouNUSA_src
		{
			get
			{
				return this._ouNUSA_src;
			}
			set
			{
				if ((this._ouNUSA_src != value))
				{
					this.OnouNUSA_srcChanging(value);
					this.SendPropertyChanging();
					this._ouNUSA_src = value;
					this.SendPropertyChanged("ouNUSA_src");
					this.OnouNUSA_srcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouNUSA_habilitado", DbType="NVarChar(1)")]
		public string ouNUSA_habilitado
		{
			get
			{
				return this._ouNUSA_habilitado;
			}
			set
			{
				if ((this._ouNUSA_habilitado != value))
				{
					this.OnouNUSA_habilitadoChanging(value);
					this.SendPropertyChanging();
					this._ouNUSA_habilitado = value;
					this.SendPropertyChanged("ouNUSA_habilitado");
					this.OnouNUSA_habilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouEsRecurso", DbType="NVarChar(1)")]
		public string ouEsRecurso
		{
			get
			{
				return this._ouEsRecurso;
			}
			set
			{
				if ((this._ouEsRecurso != value))
				{
					this.OnouEsRecursoChanging(value);
					this.SendPropertyChanging();
					this._ouEsRecurso = value;
					this.SendPropertyChanged("ouEsRecurso");
					this.OnouEsRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouDictadoNewLineMode", DbType="NVarChar(5)")]
		public string ouDictadoNewLineMode
		{
			get
			{
				return this._ouDictadoNewLineMode;
			}
			set
			{
				if ((this._ouDictadoNewLineMode != value))
				{
					this.OnouDictadoNewLineModeChanging(value);
					this.SendPropertyChanging();
					this._ouDictadoNewLineMode = value;
					this.SendPropertyChanged("ouDictadoNewLineMode");
					this.OnouDictadoNewLineModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouVocaliUSER", DbType="NVarChar(50)")]
		public string ouVocaliUSER
		{
			get
			{
				return this._ouVocaliUSER;
			}
			set
			{
				if ((this._ouVocaliUSER != value))
				{
					this.OnouVocaliUSERChanging(value);
					this.SendPropertyChanging();
					this._ouVocaliUSER = value;
					this.SendPropertyChanged("ouVocaliUSER");
					this.OnouVocaliUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouVocaliPassword", DbType="NVarChar(50)")]
		public string ouVocaliPassword
		{
			get
			{
				return this._ouVocaliPassword;
			}
			set
			{
				if ((this._ouVocaliPassword != value))
				{
					this.OnouVocaliPasswordChanging(value);
					this.SendPropertyChanging();
					this._ouVocaliPassword = value;
					this.SendPropertyChanged("ouVocaliPassword");
					this.OnouVocaliPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouVocaliServer", DbType="NVarChar(250)")]
		public string ouVocaliServer
		{
			get
			{
				return this._ouVocaliServer;
			}
			set
			{
				if ((this._ouVocaliServer != value))
				{
					this.OnouVocaliServerChanging(value);
					this.SendPropertyChanging();
					this._ouVocaliServer = value;
					this.SendPropertyChanged("ouVocaliServer");
					this.OnouVocaliServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouVocaliPort", DbType="Int")]
		public System.Nullable<int> ouVocaliPort
		{
			get
			{
				return this._ouVocaliPort;
			}
			set
			{
				if ((this._ouVocaliPort != value))
				{
					this.OnouVocaliPortChanging(value);
					this.SendPropertyChanging();
					this._ouVocaliPort = value;
					this.SendPropertyChanged("ouVocaliPort");
					this.OnouVocaliPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ouVocaliIntegracion", DbType="NVarChar(1)")]
		public string ouVocaliIntegracion
		{
			get
			{
				return this._ouVocaliIntegracion;
			}
			set
			{
				if ((this._ouVocaliIntegracion != value))
				{
					this.OnouVocaliIntegracionChanging(value);
					this.SendPropertyChanging();
					this._ouVocaliIntegracion = value;
					this.SendPropertyChanged("ouVocaliIntegracion");
					this.OnouVocaliIntegracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scValorDefaultEditor", DbType="NVarChar(5)")]
		public string scValorDefaultEditor
		{
			get
			{
				return this._scValorDefaultEditor;
			}
			set
			{
				if ((this._scValorDefaultEditor != value))
				{
					this.OnscValorDefaultEditorChanging(value);
					this.SendPropertyChanging();
					this._scValorDefaultEditor = value;
					this.SendPropertyChanged("scValorDefaultEditor");
					this.OnscValorDefaultEditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oeModalidad", DbType="VarChar(200)")]
		public string oeModalidad
		{
			get
			{
				return this._oeModalidad;
			}
			set
			{
				if ((this._oeModalidad != value))
				{
					this.OnoeModalidadChanging(value);
					this.SendPropertyChanging();
					this._oeModalidad = value;
					this.SendPropertyChanged("oeModalidad");
					this.OnoeModalidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vBuscaEnRevision")]
	public partial class vBuscaEnRevision
	{
		
		private string _AccessionNumber;
		
		private string _ExternalPatientID;
		
		private string _InternalPatientID;
		
		private string _FullName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _DOB;
		
		private string _Gender;
		
		private string _Pregnancy;
		
		private string _LastMenstruationDate;
		
		private string _StudyId;
		
		private string _RISOderId;
		
		private string _ProcedureCode;
		
		private string _ProcedureDescription;
		
		private string _Modality;
		
		private string _ReasonForExam;
		
		private string _StudyStatusCode;
		
		private string _StudyImageCount;
		
		private string _StudyTimeStamp;
		
		private string _AdmissionTimeDate;
		
		private string _VisitClass;
		
		private string _VisitNumber;
		
		private string _Priority;
		
		private string _SiteCode;
		
		private string _PrimaryLocId;
		
		private string _PrimaryLocation;
		
		private string _CurrentLocId;
		
		private string _CurrentLocation;
		
		private string _StudySiteName;
		
		private string _RequestingPhysicianId;
		
		private string _RequestingPhysician;
		
		private string _ReferringPhysicianId;
		
		private string _ReferringPhysician;
		
		private string _AttendingPhysicianId;
		
		private string _AttendingPhysician;
		
		private string _usuarioDicto;
		
		private string _usuarioDictoNombre;
		
		private string _usuarioDictoApellidoPaterno;
		
		private string _usuarioDictoApellidoMaterno;
		
		private System.Nullable<int> _STATUS;
		
		private System.Nullable<bool> _oeInterpretacionAprobada;
		
		private string _oeComentarioValidacion;
		
		private string _usuarioRevisoID;
		
		private string _usuarioRevisoNombre;
		
		private string _usuarioRevisoApellidoPaterno;
		
		private string _usuarioRevisoApellidoMaterno;
		
		private bool _bkStatus;
		
		private System.Nullable<System.DateTime> _fechayhora;
		
		private int _SolicitaRevision;
		
		public vBuscaEnRevision()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessionNumber", DbType="NVarChar(50)")]
		public string AccessionNumber
		{
			get
			{
				return this._AccessionNumber;
			}
			set
			{
				if ((this._AccessionNumber != value))
				{
					this._AccessionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExternalPatientID", DbType="NVarChar(50)")]
		public string ExternalPatientID
		{
			get
			{
				return this._ExternalPatientID;
			}
			set
			{
				if ((this._ExternalPatientID != value))
				{
					this._ExternalPatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalPatientID", DbType="NVarChar(50)")]
		public string InternalPatientID
		{
			get
			{
				return this._InternalPatientID;
			}
			set
			{
				if ((this._InternalPatientID != value))
				{
					this._InternalPatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(453) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(301) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="VarChar(10)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pregnancy", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Pregnancy
		{
			get
			{
				return this._Pregnancy;
			}
			set
			{
				if ((this._Pregnancy != value))
				{
					this._Pregnancy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMenstruationDate", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string LastMenstruationDate
		{
			get
			{
				return this._LastMenstruationDate;
			}
			set
			{
				if ((this._LastMenstruationDate != value))
				{
					this._LastMenstruationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudyId", DbType="NVarChar(200)")]
		public string StudyId
		{
			get
			{
				return this._StudyId;
			}
			set
			{
				if ((this._StudyId != value))
				{
					this._StudyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RISOderId", DbType="NVarChar(50)")]
		public string RISOderId
		{
			get
			{
				return this._RISOderId;
			}
			set
			{
				if ((this._RISOderId != value))
				{
					this._RISOderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureCode", DbType="NVarChar(50)")]
		public string ProcedureCode
		{
			get
			{
				return this._ProcedureCode;
			}
			set
			{
				if ((this._ProcedureCode != value))
				{
					this._ProcedureCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureDescription", DbType="NVarChar(100)")]
		public string ProcedureDescription
		{
			get
			{
				return this._ProcedureDescription;
			}
			set
			{
				if ((this._ProcedureDescription != value))
				{
					this._ProcedureDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modality", DbType="NVarChar(50)")]
		public string Modality
		{
			get
			{
				return this._Modality;
			}
			set
			{
				if ((this._Modality != value))
				{
					this._Modality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonForExam", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ReasonForExam
		{
			get
			{
				return this._ReasonForExam;
			}
			set
			{
				if ((this._ReasonForExam != value))
				{
					this._ReasonForExam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudyStatusCode", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string StudyStatusCode
		{
			get
			{
				return this._StudyStatusCode;
			}
			set
			{
				if ((this._StudyStatusCode != value))
				{
					this._StudyStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudyImageCount", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string StudyImageCount
		{
			get
			{
				return this._StudyImageCount;
			}
			set
			{
				if ((this._StudyImageCount != value))
				{
					this._StudyImageCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudyTimeStamp", DbType="VarChar(21)")]
		public string StudyTimeStamp
		{
			get
			{
				return this._StudyTimeStamp;
			}
			set
			{
				if ((this._StudyTimeStamp != value))
				{
					this._StudyTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdmissionTimeDate", DbType="VarChar(21)")]
		public string AdmissionTimeDate
		{
			get
			{
				return this._AdmissionTimeDate;
			}
			set
			{
				if ((this._AdmissionTimeDate != value))
				{
					this._AdmissionTimeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitClass", DbType="NVarChar(1)")]
		public string VisitClass
		{
			get
			{
				return this._VisitClass;
			}
			set
			{
				if ((this._VisitClass != value))
				{
					this._VisitClass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitNumber", DbType="NVarChar(50)")]
		public string VisitNumber
		{
			get
			{
				return this._VisitNumber;
			}
			set
			{
				if ((this._VisitNumber != value))
				{
					this._VisitNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteCode", DbType="NVarChar(12)")]
		public string SiteCode
		{
			get
			{
				return this._SiteCode;
			}
			set
			{
				if ((this._SiteCode != value))
				{
					this._SiteCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryLocId", DbType="NVarChar(12)")]
		public string PrimaryLocId
		{
			get
			{
				return this._PrimaryLocId;
			}
			set
			{
				if ((this._PrimaryLocId != value))
				{
					this._PrimaryLocId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryLocation", DbType="NVarChar(12)")]
		public string PrimaryLocation
		{
			get
			{
				return this._PrimaryLocation;
			}
			set
			{
				if ((this._PrimaryLocation != value))
				{
					this._PrimaryLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentLocId", DbType="NVarChar(100)")]
		public string CurrentLocId
		{
			get
			{
				return this._CurrentLocId;
			}
			set
			{
				if ((this._CurrentLocId != value))
				{
					this._CurrentLocId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentLocation", DbType="NVarChar(100)")]
		public string CurrentLocation
		{
			get
			{
				return this._CurrentLocation;
			}
			set
			{
				if ((this._CurrentLocation != value))
				{
					this._CurrentLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudySiteName", DbType="NVarChar(12)")]
		public string StudySiteName
		{
			get
			{
				return this._StudySiteName;
			}
			set
			{
				if ((this._StudySiteName != value))
				{
					this._StudySiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestingPhysicianId", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string RequestingPhysicianId
		{
			get
			{
				return this._RequestingPhysicianId;
			}
			set
			{
				if ((this._RequestingPhysicianId != value))
				{
					this._RequestingPhysicianId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestingPhysician", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string RequestingPhysician
		{
			get
			{
				return this._RequestingPhysician;
			}
			set
			{
				if ((this._RequestingPhysician != value))
				{
					this._RequestingPhysician = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferringPhysicianId", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ReferringPhysicianId
		{
			get
			{
				return this._ReferringPhysicianId;
			}
			set
			{
				if ((this._ReferringPhysicianId != value))
				{
					this._ReferringPhysicianId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferringPhysician", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ReferringPhysician
		{
			get
			{
				return this._ReferringPhysician;
			}
			set
			{
				if ((this._ReferringPhysician != value))
				{
					this._ReferringPhysician = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendingPhysicianId", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string AttendingPhysicianId
		{
			get
			{
				return this._AttendingPhysicianId;
			}
			set
			{
				if ((this._AttendingPhysicianId != value))
				{
					this._AttendingPhysicianId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendingPhysician", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string AttendingPhysician
		{
			get
			{
				return this._AttendingPhysician;
			}
			set
			{
				if ((this._AttendingPhysician != value))
				{
					this._AttendingPhysician = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioDicto", DbType="NVarChar(50)")]
		public string usuarioDicto
		{
			get
			{
				return this._usuarioDicto;
			}
			set
			{
				if ((this._usuarioDicto != value))
				{
					this._usuarioDicto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioDictoNombre", DbType="NVarChar(150)")]
		public string usuarioDictoNombre
		{
			get
			{
				return this._usuarioDictoNombre;
			}
			set
			{
				if ((this._usuarioDictoNombre != value))
				{
					this._usuarioDictoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioDictoApellidoPaterno", DbType="NVarChar(150)")]
		public string usuarioDictoApellidoPaterno
		{
			get
			{
				return this._usuarioDictoApellidoPaterno;
			}
			set
			{
				if ((this._usuarioDictoApellidoPaterno != value))
				{
					this._usuarioDictoApellidoPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioDictoApellidoMaterno", DbType="NVarChar(150)")]
		public string usuarioDictoApellidoMaterno
		{
			get
			{
				return this._usuarioDictoApellidoMaterno;
			}
			set
			{
				if ((this._usuarioDictoApellidoMaterno != value))
				{
					this._usuarioDictoApellidoMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oeInterpretacionAprobada", DbType="Bit")]
		public System.Nullable<bool> oeInterpretacionAprobada
		{
			get
			{
				return this._oeInterpretacionAprobada;
			}
			set
			{
				if ((this._oeInterpretacionAprobada != value))
				{
					this._oeInterpretacionAprobada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oeComentarioValidacion", DbType="NVarChar(MAX)")]
		public string oeComentarioValidacion
		{
			get
			{
				return this._oeComentarioValidacion;
			}
			set
			{
				if ((this._oeComentarioValidacion != value))
				{
					this._oeComentarioValidacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioRevisoID", DbType="NVarChar(50)")]
		public string usuarioRevisoID
		{
			get
			{
				return this._usuarioRevisoID;
			}
			set
			{
				if ((this._usuarioRevisoID != value))
				{
					this._usuarioRevisoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioRevisoNombre", DbType="NVarChar(150)")]
		public string usuarioRevisoNombre
		{
			get
			{
				return this._usuarioRevisoNombre;
			}
			set
			{
				if ((this._usuarioRevisoNombre != value))
				{
					this._usuarioRevisoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioRevisoApellidoPaterno", DbType="NVarChar(150)")]
		public string usuarioRevisoApellidoPaterno
		{
			get
			{
				return this._usuarioRevisoApellidoPaterno;
			}
			set
			{
				if ((this._usuarioRevisoApellidoPaterno != value))
				{
					this._usuarioRevisoApellidoPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioRevisoApellidoMaterno", DbType="NVarChar(150)")]
		public string usuarioRevisoApellidoMaterno
		{
			get
			{
				return this._usuarioRevisoApellidoMaterno;
			}
			set
			{
				if ((this._usuarioRevisoApellidoMaterno != value))
				{
					this._usuarioRevisoApellidoMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bkStatus", DbType="Bit NOT NULL")]
		public bool bkStatus
		{
			get
			{
				return this._bkStatus;
			}
			set
			{
				if ((this._bkStatus != value))
				{
					this._bkStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechayhora", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechayhora
		{
			get
			{
				return this._fechayhora;
			}
			set
			{
				if ((this._fechayhora != value))
				{
					this._fechayhora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SolicitaRevision", DbType="Int NOT NULL")]
		public int SolicitaRevision
		{
			get
			{
				return this._SolicitaRevision;
			}
			set
			{
				if ((this._SolicitaRevision != value))
				{
					this._SolicitaRevision = value;
				}
			}
		}
	}
	
	public partial class spProcedeBloqueoResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public spProcedeBloqueoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
